server:
  port: 8088
spring:
  datasource:
#    url: jdbc:h2:./devdb
    driverClassName: org.h2.Driver
    username: root
    password: root
    url: jdbc:h2:mem:devdb
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
    properties:
      javax:
        persistence:
          validation:
            mode: none

#  ==========================
#  CONDITION EVALUATION DELTA
#  ==========================
  devtools:
    restart:
      log-condition-evaluation-delta: false